import React, { useState, useEffect } from "react";
import { Card, Loader, FormField } from "../components";

const RenderCards = ({ data, title }) => {
	if (data?.length > 0) {
		return data.map((post) => <Card key={post._id} {...post} />);
	}
	return <h2 className="mt-5 font-bold uppercase">{title} </h2>;
};

function Home() {
	const [loading, setLoading] = useState(false);
	const [allPosts, setAllPosts] = useState(null);
	const [searchText, setSearchText] = useState("ss");
	return (
		<section className=" bg-red-50 mx-auto">
			<div>
				<h1 className="font-extrabold text-[32px]"> The Comminity ShowCase</h1>
				<p className="mt-2 font-semibold text-green-900 text-[14px] max-w-screen-lg">
					Browse through a collection of imaginative and visually stunning images
					generated by DALL-E AI
				</p>
			</div>
			<div className="mt-16">
				<FormField />
			</div>
			<div className="mt-10">
				{loading ? (
					<div>
						<Loader />
					</div>
				) : (
					<>
						{searchText && (
							<h2 className="font-medium  text-lg mb-3">
								Showing Results For <span className=""> {searchText}</span>
							</h2>
						)}
						<div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
							{searchText ? (
								<RenderCards data={[]} title="No search results found" />
							) : (
								<RenderCards data={[]} title="No posts  found" />
							)}
						</div>
					</>
				)}
			</div>
		</section>
	);
}

export default Home;
